### ISSUE TITLE
Unable to dismiss cart

### ISSUE THREAD

**Issue by kurtschlatzer** [snipcart/hugo-forestry#1]
Need the ability to dismiss cart to add multiple items -- i.e. "Continue Shopping"

**Comment by thatfrankdev** [comment]
Hi @kurtschlatzer,

Sorry for the lack of response here, as we do not closely monitor issues raised on demo repositories.

In the fall of 2019, we released Snipcart v3, that offers much better UX and customizability. You can take a look at it here: https://docs.snipcart.com/v3/
